apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sampleone
  description: To test the component creation.
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: Devops
